# Generated by Django 3.0.2 on 2020-03-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='data_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_anterior',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_novo',
            field=models.DateTimeField(),
        ),
    ]
