# Generated by Django 3.0.3 on 2020-03-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200320_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='data_update',
            field=models.DateTimeField(verbose_name='Última atualização'),
        ),
    ]
