# Generated by Django 3.0.2 on 2020-04-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200322_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='api.Cidade'),
        ),
    ]
