# Generated by Django 3.0.5 on 2020-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('suspeitos', models.IntegerField()),
                ('confirmados', models.IntegerField()),
                ('descartados', models.IntegerField()),
                ('obitos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=30)),
            ],
        ),
    ]
