# Generated by Django 3.0.5 on 2020-05-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='recuperados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
